=== sourcemeta/registry/collections/sourcemeta/registry/schemas/configuration/configuration.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "The Sourcemeta Registry configuration file format",
  "description": "The configuration file format used to configured Registry instances",
  "type": "object",
  "required": [ "url" ],
  "properties": {
    "extends": {
      "$ref": "./extends.json"
    },
    "contents": {
      "$ref": "./contents.json",
      "properties": {
        "self": false
      }
    },
    "html": {
      "type": [ "object", "boolean" ],
      "properties": {
        "description": {
          "type": "string"
        },
        "action": {
          "type": "object",
          "required": [ "title", "url", "icon" ],
          "properties": {
            "title": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            },
            "url": {
              "$ref": "../../../std/v0.0.1/schemas/url.json"
            }
          },
          "additionalProperties": false
        },
        "head": {
          "type": "string"
        },
        "hero": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "url": {
      "$ref": "../../../std/v0.0.1/schemas/url.json"
    }
  },
  "additionalProperties": false
}

=== sourcemeta/registry/test/sandbox/registry-html.json
{
  "url": "http://localhost:8000",
  "html": {
    "hero": "<p class=\"mb-0\">A sample schema registry sandbox for testing purposes</p>",
    "action": {
      "title": "Star on GitHub",
      "url": "https://github.com/sourcemeta/registry",
      "icon": "github"
    }
  },
  "extends": [
    "@geojson/v1.0.5",
    "@sourcemeta/registry"
  ],
  "contents": {
    "test": {
      "title": "Test",
      "description": "A directory full of testing schemas",
      "contents": {
        "extension": {
          "baseUri": "https://example.com/extension",
          "path": "./schemas/test/extension"
        },
        "schemas": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/folder",
          "defaultDialect": "http://json-schema.org/draft-07/schema#",
          "resolve": {
            "https://other.com/single.json": "/test/bundling/single.json"
          }
        },
        "camelcase": {
          "contents": {
            "test": {
              "baseUri": "https://sourcemeta.com/camelcase",
              "path": "./schemas/test/camelcase"
            }
          }
        },
        "v2.0": {
          "baseUri": "https://example.com/schemas",
          "path": "./schemas/test/v2.0"
        },
        "bundling": {
          "baseUri": "https://example.com/bundling",
          "path": "./schemas/test/bundling"
        },
        "doc": {
          "title": "A sample schema folder",
          "description": "For testing purposes",
          "github": "sourcemeta/registry",
          "baseUri": "https://example.com/doc",
          "path": "./schemas/test/doc"
        },
        "hyper": {
          "baseUri": "https://example.com/hyper",
          "path": "./schemas/test/hyper"
        },
        "same": {
          "baseUri": "http://localhost:8000/same",
          "path": "./schemas/test/same"
        },
        "no-blaze": {
          "baseUri": "https://other.com",
          "path": "./schemas/test/no-blaze",
          "x-sourcemeta-registry:evaluate": false
        },
        "no-serve": {
          "path": "./schemas/test/no-serve",
          "x-sourcemeta-registry:protected": true,
          "x-sourcemeta-registry:alert": "This collection is private"
        }
      }
    }
  }
}
