=== sourcemeta/registry/schemas/configuration.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:sourcemeta:registry/configuration.json",
  "type": "object",
  "required": [ "url", "port", "schemas" ],
  "properties": {
    "title": {
      "default": "Sourcemeta",
      "$ref": "#/$defs/text"
    },
    "description": {
      "default": "The next-generation JSON Schema Registry",
      "$ref": "#/$defs/text"
    },
    "extends": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "action": {
      "type": "object",
      "required": [ "title", "url" ],
      "properties": {
        "title": {
          "$ref": "#/$defs/text"
        },
        "icon": {
          "enum": [ "github", "link" ]
        },
        "url": {
          "$ref": "#/$defs/http-url"
        }
      },
      "additionalProperties": false
    },
    "head": {
      "type": "string"
    },
    "hero": {
      "type": "string"
    },
    "pages": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/entry-path"
      },
      "additionalProperties": {
        "type": "object",
        "minProperties": 1,
        "properties": {
          "title": {
            "$ref": "#/$defs/text"
          },
          "description": {
            "$ref": "#/$defs/text"
          },
          "email": {
            "type": "string",
            "pattern": "^[a-z0-9._+-]+@[a-z0-9.-]+\\.[a-z]{2,}$",
            "format": "email"
          },
          "github": {
            "type": "string",
            "pattern": "^[a-z0-9-]+(/[a-z0-9-]+)?$"
          },
          "website": {
            "$ref": "#/$defs/http-url"
          }
        },
        "additionalProperties": false
      }
    },
    "port": {
      "type": "integer",
      "minimum": 0
    },
    "schemas": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/entry-path"
      },
      "additionalProperties": {
        "type": "object",
        "required": [ "base", "path" ],
        "properties": {
          "x-sourcemeta-registry:blaze-exhaustive": {
            "type": "boolean"
          },
          "base": {
            "$ref": "#/$defs/uri"
          },
          "defaultDialect": {
            "type": "string",
            "minLength": 1
          },
          "path": {
            "type": "string",
            "pattern": "^\\S.*\\S$",
            "minLength": 1
          },
          "rebase": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "object",
              "required": [ "from", "to" ],
              "properties": {
                "from": {
                  "$ref": "#/$defs/uri"
                },
                "to": {
                  "$ref": "#/$defs/uri"
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      }
    },
    "url": {
      "$ref": "#/$defs/http-url"
    }
  },
  "additionalProperties": false,
  "$defs": {
    "entry-path": {
      "pattern": "^[a-z0-9][a-z0-9-/.]*$"
    },
    "http-url": {
      "type": "string",
      "pattern": "^https?:\\/\\/[a-z0-9-.:/]+$",
      "format": "url"
    },
    "text": {
      "type": "string",
      "pattern": "^\\S.*\\S$",
      "minLength": 1
    },
    "uri": {
      "type": "string",
      "pattern": "^\\S.*\\S?$",
      "format": "uri",
      "minLength": 1
    }
  }
}

=== sourcemeta/registry/test/sandbox/configuration.json
{
  "url": "http://localhost:8000",
  "port": 8000,
  "hero": "<p class=\"mb-0\">A sample schema registry sandbox for testing purposes</p>",
  "action": {
    "title": "Star on GitHub",
    "url": "https://github.com/sourcemeta/registry",
    "icon": "github"
  },
  "pages": {
    "example": {
      "title": "Sourcemeta",
      "description": "My description",
      "email": "hello@sourcemeta.com",
      "github": "sourcemeta",
      "website": "https://www.sourcemeta.com"
    },
    "doc": {
      "title": "A sample schema folder",
      "description": "For testing purposes",
      "github": "sourcemeta/registry"
    }
  },
  "schemas": {
    "example/extension": {
      "base": "https://example.com/extension",
      "path": "./schemas/example/extension"
    },
    "example/schemas": {
      "base": "https://example.com/schemas",
      "path": "./schemas/example/folder",
      "defaultDialect": "http://json-schema.org/draft-07/schema#",
      "rebase": [
        { "from": "https://other.com", "to": "/example/bundling" }
      ]
    },
    "example/camelcase/test": {
      "base": "https://sourcemeta.com/camelcase",
      "path": "./schemas/example/camelcase"
    },
    "example/v2.0": {
      "base": "https://example.com/schemas",
      "path": "./schemas/example/v2.0"
    },
    "example/bundling": {
      "base": "https://example.com/bundling",
      "path": "./schemas/example/bundling"
    },
    "doc": {
      "base": "https://example.com/doc",
      "path": "./schemas/doc"
    },
    "hyper": {
      "base": "https://example.com/hyper",
      "path": "./schemas/hyper"
    }
  }
}
